name: Windows Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x86
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools requests
        pip install PyInstaller==4.2
    - name: Generate binary
      run: |
        pyinstaller --onefile -n tle_gen tle_gen.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TLE_Generator.windows
        path: |
          dist/tle_gen.exe
          satellites.txt
